In [2]:
import pyspark as ps
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np
import seaborn as sns

In [3]:
budget_pd = pd.read_csv('../data/Selected and Combined Spending Data.csv')

In [4]:
spark = (ps.sql.SparkSession
         .builder
         .master('local[4]')
         .appName('budget_data')
         .getOrCreate()
        )
sc = spark.sparkContext

spark_population = spark.read.csv('../data/population_by_county_1970_to_2018.csv',
                    header=True,
                    quote='"',
                    sep=",",
                    inferSchema=True)

spark_population.createOrReplaceTempView('population_tempview')

In [6]:
query = '''
select *
from population_tempview
WHERE `Year` >2002
AND `Year` < 2019
ORDER BY `Year`, `County`
'''

population_sql = spark.sql(query)
population_sql.show()
population_pd = population_sql.toPandas()

+------------+----+----------+
|      County|Year|Population|
+------------+----+----------+
|     Alameda|2003|   1467892|
|      Alpine|2003|      1248|
|      Amador|2003|     36656|
|       Butte|2003|    209389|
|   Calaveras|2003|     42651|
|      Colusa|2003|     19538|
|Contra Costa|2003|    984256|
|   Del Norte|2003|     27744|
|   El Dorado|2003|    166195|
|      Fresno|2003|    837256|
|       Glenn|2003|     26974|
|    Humboldt|2003|    129468|
|    Imperial|2003|    149041|
|        Inyo|2003|     18461|
|        Kern|2003|    707111|
|       Kings|2003|    136710|
|        Lake|2003|     61492|
|      Lassen|2003|     33828|
| Los Angeles|2003|   9756914|
|      Madera|2003|    130641|
+------------+----+----------+
only showing top 20 rows

In [9]:
budget_per_capita_pd = budget_pd.join(population_pd)
budget_per_capita_pd.head(60)

,Entity Name,Fiscal Year,Police Protection_Total,Mental Health_Total,Drug and Alcohol Abuse Services_Total,County,Year,Population
0,Alameda,2003,67620724,162111429.0,28910904.0,Alameda,2003.0,1467892.0
1,Alpine,2003,1610553,148701.0,500356.0,Alpine,2003.0,1248.0
2,Amador,2003,5715469,1885165.0,849770.0,Amador,2003.0,36656.0
3,Butte,2003,11450959,28935820.0,4019764.0,Butte,2003.0,209389.0
4,Calaveras,2003,5672737,2007571.0,875481.0,Calaveras,2003.0,42651.0
5,Colusa,2003,3159671,2499952.0,1782027.0,Colusa,2003.0,19538.0
6,Contra Costa,2003,78549758,88054807.0,19305613.0,Contra Costa,2003.0,984256.0
7,Del Norte,2003,3004638,3055510.0,654251.0,Del Norte,2003.0,27744.0
8,El Dorado,2003,19796653,8408390.0,3046411.0,El Dorado,2003.0,166195.0
9,Fresno,2003,67466928,65272470.0,0.0,Fresno,2003.0,837256.0
10,Glenn,2003,4251992,3594298.0,1447071.0,Glenn,2003.0,26974.0
11,Humboldt,2003,10179118,18696775.0,2590703.0,Humboldt,2003.0,129468.0
12,Imperial,2003,12738280,11720110.0,2119301.0,Imperial,2003.0,149041.0
13,Inyo,2003,3932627,3060994.0,702535.0,Inyo,2003.0,18461.0
14,Kern,2003,56700193,59119640.0,10021022.0,Kern,2003.0,707111.0
15,Kings,2003,7884414,8203505.0,1778267.0,Kings,2003.0,136710.0
16,Lake,2003,7647010,6242206.0,2134868.0,Lake,2003.0,61492.0
17,Lassen,2003,2019785,2870974.0,1361576.0,Lassen,2003.0,33828.0
18,Los Angeles,2003,1007572763,945781445.0,149581202.0,Los Angeles,2003.0,9756914.0
19,Madera,2003,8224549,8599753.0,1654343.0,Madera,2003.0,130641.0
20,Marin,2003,18801342,23931544.0,6167598.0,Marin,2003.0,247342.0
21,Mariposa,2003,3282766,1455045.0,592834.0,Mariposa,2003.0,17612.0
22,Mendocino,2003,7930285,12310381.0,2589596.0,Mendocino,2003.0,87764.0
23,Merced,2003,10645728,17207199.0,3121560.0,Merced,2003.0,225946.0
24,Modoc,2003,1801129,1273738.0,733498.0,Modoc,2003.0,9456.0
25,Mono,2003,2929163,1114720.0,740642.0,Mono,2003.0,13478.0
26,Monterey,2003,29670460,26684680.0,4819777.0,Monterey,2003.0,410276.0
27,Napa,2003,13449003,13194410.0,3747799.0,Napa,2003.0,128683.0
28,Nevada,2003,10772748,4576571.0,2136289.0,Nevada,2003.0,95277.0
29,Orange,2003,227689394,155470232.0,38814007.0,Orange,2003.0,2944565.0
30,Placer,2003,50767361,21432866.0,0.0,Placer,2003.0,283703.0
31,Plumas,2003,4847346,2207001.0,1384322.0,Plumas,2003.0,20722.0
32,Riverside,2003,199290902,82587112.0,16006438.0,Riverside,2003.0,1730219.0
33,Sacramento,2003,179853799,27998807.0,19185351.0,Sacramento,2003.0,1307189.0
34,San Benito,2003,3552413,2349221.0,849236.0,San Benito,2003.0,55330.0
35,San Bernardino,2003,181707404,112362437.0,19196909.0,San Bernardino,2003.0,1825379.0
36,San Diego,2003,184520110,234883823.0,51820773.0,San Diego,2003.0,2927216.0
37,San Joaquin,2003,37461159,60203002.0,14573686.0,San Francisco,2003.0,782599.0
38,San Luis Obispo,2003,19518428,20774740.0,4632359.0,San Joaquin,2003.0,612295.0
39,San Mateo,2003,49817476,71567633.0,17216299.0,San Luis Obispo,2003.0,254583.0
40,Santa Barbara,2003,39760736,39741898.0,10350096.0,San Mateo,2003.0,704014.0
41,Santa Clara,2003,93537797,192275635.0,39531711.0,Santa Barbara,2003.0,407828.0
42,Santa Cruz,2003,19831732,31552556.0,6450219.0,Santa Clara,2003.0,1693752.0
43,Shasta,2003,14342669,18339737.0,3419042.0,Santa Cruz,2003.0,255368.0
44,Sierra,2003,1978345,392354.0,599094.0,Shasta,2003.0,170782.0
45,Siskiyou,2003,8465358,6339258.0,1313579.0,Sierra,2003.0,3555.0
46,Solano,2003,44119150,38057657.0,4536708.0,Siskiyou,2003.0,44491.0
47,Sonoma,2003,44380422,37558274.0,11168082.0,Solano,2003.0,407882.0
48,Stanislaus,2003,32526451,53649815.0,6344730.0,Sonoma,2003.0,467139.0
49,Sutter,2003,4828724,15539921.0,0.0,Stanislaus,2003.0,478283.0
50,Tehama,2003,5512369,6896817.0,1488624.0,Sutter,2003.0,83018.0
51,Trinity,2003,2417792,2007615.0,847895.0,Tehama,2003.0,57847.0
52,Tulare,2003,23358578,33911642.0,8776200.0,Trinity,2003.0,13273.0
53,Tuolumne,2003,7643773,4885216.0,810134.0,Tulare,2003.0,385769.0
54,Ventura,2003,89912232,44349665.0,15070495.0,Tuolumne,2003.0,56177.0
55,Yolo,2003,6205625,0.0,3507093.0,Ventura,2003.0,784632.0
56,Yuba,2003,6894491,0.0,0.0,Yolo,2003.0,180798.0
57,Alameda,2004,72540104,167862041.0,27567999.0,Yuba,2003.0,63349.0
58,Alpine,2004,1411586,137872.0,601698.0,Alameda,2004.0,1466407.0
59,Amador,2004,6210532,1714272.0,873767.0,Alpine,2004.0,1257.0